"""
Script to plot the ground state histogram from the MCMC data.
Reads the path configurations saved by ground.f and creates a histogram
showing the position probability distribution of the ground state.
"""

import numpy as np
import matplotlib.pyplot as plt

def read_ground_state_data(filename='ground_state_paths.txt'):
    """
    Read the ground state path data from the file generated by ground.f
    """
    print(f"Reading data from {filename}...")
    
    # Read the data, skipping the comment lines
    data = []
    n_conf = None
    nt = None
    bhw = None
    
    with open(filename, 'r') as f:
        lines = f.readlines()
        
        # Parse header information
        for line in lines[:3]:
            if 'n_conf' in line and 'nt' in line:
                parts = line.split()
                n_conf = int(parts[3])
                nt = int(parts[6])
            elif 'bhw' in line:
                parts = line.split()
                bhw = float(parts[3])
        
        # Read numerical data
        for line in lines[3:]:
            if line.strip() and not line.startswith('#'):
                data.append(float(line.strip()))
    
    print(f"Parameters: n_conf={n_conf}, nt={nt}, bhw={bhw}")
    print(f"Total data points read: {len(data)}")
    
    # Reshape data into matrix: n_conf x nt
    if len(data) != n_conf * nt:
        print(f"Warning: Expected {n_conf * nt} data points, got {len(data)}")
        
    path_matrix = np.array(data).reshape(n_conf, nt)
    
    return path_matrix, n_conf, nt, bhw

def plot_ground_state_histogram(path_matrix, n_conf, nt, bhw, bins=200):
    """
    Create and save the ground state histogram
    """
    print("Creating histogram...")
    
    # Flatten all path values for the histogram
    all_positions = path_matrix.flatten()
    
    plt.figure(figsize=(12, 8))
    
    # Main histogram plot (now full size)
    n, bins_edges, patches = plt.hist(all_positions, bins=bins, density=True, 
                                      alpha=0.7, color='blue', edgecolor='black')
    
    # Theoretical ground state wavefunction for comparison
    x_theory = np.linspace(min(all_positions), max(all_positions), 1000)
    psi_squared_theory = np.exp(-x_theory**2) / np.sqrt(np.pi)
    
    plt.plot(x_theory, psi_squared_theory, 'r-', linewidth=2, 
             label=r'Theoretical $|\psi_0(x)|^2$')
    
    plt.title(f'Ground State Position Histogram ($\\beta\\hbar\\omega$ = {bhw})')
    plt.xlabel('Position x')
    plt.ylabel('Probability Density')
    plt.legend()
    plt.grid(True, alpha=0.3)
    
    # Add statistics as text box in top-right corner
    stats_text = (
        f"Configurations: {n_conf}\n"
        f"Time slices: {nt}\n"
        f"Data points: {len(all_positions)}\n"
        f"$\\beta\\hbar\\omega$ = {bhw}\n"
        f"$\\mu$ = {np.mean(all_positions):.4f}\n"
        f"$\\sigma^2$ = {np.var(all_positions):.4f}"
    )

    # Create text box with white background and black border
    props = dict(boxstyle='round', facecolor='white', alpha=0.8, edgecolor='black')
    plt.text(0.98, 0.98, stats_text, transform=plt.gca().transAxes, fontsize=10,
             verticalalignment='top', horizontalalignment='right', bbox=props)
    
    # Save the plot
    filename = f'ground_state_histogram_bhw{bhw}.png'
    plt.savefig(filename, dpi=300, bbox_inches='tight')
    print(f"Histogram saved as {filename}")
    
    plt.show()
    
    return all_positions

def main():
    """
    Main function to read data and create histogram
    """
    try:
        # Read the data
        path_matrix, n_conf, nt, bhw = read_ground_state_data()
        
        # Create the histogram
        all_positions = plot_ground_state_histogram(path_matrix, n_conf, nt, bhw)
        
    except FileNotFoundError:
        print("Error: ground_state_paths.txt file not found!")
        print("Please run the Fortran program ground.f first to generate the data.")
    except Exception as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    main()